DROP TABLE REVIEW_REPORT;
DROP TABLE REVIEW_TAG;
DROP TABLE TAG;
DROP TABLE REVIEW;
DROP SEQUENCE REVIEW_SEQ;
DROP SEQUENCE TAG_SEQ;

-- 시퀀스
CREATE SEQUENCE REVIEW_SEQ  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TAG_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 주문헤더
CREATE TABLE REVIEW (
  REVIEW_ID     NUMBER(10)           NOT NULL,
  PRODUCT_ID     NUMBER(10)           NOT NULL,
  BUYER_ID     NUMBER(10)           NOT NULL,
  ORDER_ITEM_ID     NUMBER(10)           NOT NULL,
  CONTENT			 clob,
  SCORE        NUMBER(2,1)          NOT NULL,
  SELLER_RECOYN char(1)             DEFAULT 'N',
  STATUS       VARCHAR2(11)         DEFAULT 'R0201',
  CREATE_DATE  timestamp            default systimestamp,
  UPDATE_DATE  timestamp,
  CONSTRAINT PK_REVIEW PRIMARY KEY (REVIEW_ID),
  CONSTRAINT CK_REVIEW_SCORE CHECK (SCORE > 0 AND SCORE <= 5),
  CONSTRAINT CK_REVIEW_seller CHECK (SELLER_RECOYN IN ('Y','N'))
);

ALTER TABLE REVIEW
  ADD CONSTRAINT FK_REVIEW_product
  FOREIGN KEY (PRODUCT_ID) REFERENCES product (PRODUCT_ID);

ALTER TABLE REVIEW
  ADD CONSTRAINT FK_REVIEW_BUYER
  FOREIGN KEY (BUYER_ID) REFERENCES MEMBER (MEMBER_ID);

ALTER TABLE REVIEW
  ADD CONSTRAINT FK_REVIEW_ORDER
  FOREIGN KEY (ORDER_ITEM_ID) REFERENCES ORDER_ITEMS (ORDER_ITEM_ID);



/* ---- TAG (리뷰에 사용할 태그) ---------------------------- */
CREATE TABLE TAG (
  TAG_ID       NUMBER(10)                  NOT NULL,
  LABEL        VARCHAR2(50),
  SLUG         VARCHAR2(50),
  TCATEGORY    VARCHAR2(11),
  COMMONYN     CHAR(1),
  USEYN        CHAR(1)        DEFAULT 'Y'  NOT NULL,              -- 'Y'/'N'
  RECOYN       CHAR(1)        DEFAULT 'N'  NOT NULL,              -- 'Y'/'N'
  CREATE_DATE  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATE_DATE  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_TAG                 PRIMARY KEY (TAG_ID),
  CONSTRAINT FK_TAG_TCATEGORY       FOREIGN KEY (TCATEGORY) REFERENCES CODE (CODE_ID) ON DELETE CASCADE,
  CONSTRAINT CK_TAG_COMMONYN        CHECK (COMMONYN IN ('Y','N')),
  CONSTRAINT CK_TAG_USEYN           CHECK (USEYN    IN ('Y','N')),
  CONSTRAINT CK_TAG_RECOYN          CHECK (RECOYN   IN ('Y','N'))
);

/* ---- REVIEW_TAG (리뷰 작성시 선택한 태그) ---------------- */
CREATE TABLE REVIEW_TAG (
  REVIEW_ID    NUMBER(10)  NOT NULL,
  TAG_ID       NUMBER(10)  NOT NULL,
  SORT_ORDER   NUMBER(2),
  CONSTRAINT PK_REVIEW_TAG            PRIMARY KEY (REVIEW_ID, TAG_ID),
  CONSTRAINT FK_REVIEW_TAG_REVIEW     FOREIGN KEY (REVIEW_ID) REFERENCES REVIEW (REVIEW_ID) ON DELETE CASCADE,
  CONSTRAINT FK_REVIEW_TAG_TAG        FOREIGN KEY (TAG_ID)    REFERENCES TAG    (TAG_ID)    ON DELETE CASCADE
);

/* ---- REVIEW_REPORT (리뷰 신고) --------------------------- */
CREATE TABLE REVIEW_REPORT (
  REVIEW_ID    NUMBER(10)  NOT NULL,
  MEMBER_ID    NUMBER(10)  NOT NULL,
  REASON       VARCHAR2(300),
  REPORT_DATE  TIMESTAMP   DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_REVIEW_REPORT         PRIMARY KEY (REVIEW_ID, MEMBER_ID),
  CONSTRAINT FK_REVIEW_REPORT_REVIEW  FOREIGN KEY (REVIEW_ID) REFERENCES REVIEW (REVIEW_ID) ON DELETE CASCADE,
  CONSTRAINT FK_REVIEW_REPORT_MEMBER  FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE
);



/* ===================== B0101 지역 ===================== */
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
VALUES (TAG_SEQ.NEXTVAL, '#역세권_핫플',   'near-subway',        'B0101', 'N', 'Y', 'N');
INSERT INTO TAG  (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
VALUES (TAG_SEQ.NEXTVAL, '#시원한_바다_뷰', 'seaside-area',       'B0101', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#산자락_힐링스폿',   'mountain-area',      'B0101', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#시장_골목투어',   'market-area',        'B0101', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#공원_피크닉존',   'park-adjacent',      'B0101', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#도심_핫플',     'downtown',           'B0101', 'N', 'Y', 'N');

/* ===================== B0102 반려동물 ===================== */
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#강아지_출입_가능', 'pet-dogs-allowed',   'B0102', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#고양이_출입_가능', 'pet-cats-allowed',   'B0102', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#대형견_OK',      'large-dogs-ok',      'B0102', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#펫전용_좌석',   'pet-seating',       'B0102', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#펫프렌들리',    'pet-friendly-stay', 'B0102', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#펫키트_무료제공',   'pet-kit-provided',   'B0102', 'N', 'Y', 'N');

/* ===================== B0103 맛집 ===================== */
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#매운맛_끝판왕',      'spicy',              'B0103', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#고기_푸짐맛집',     'meat-restaurant',    'B0103', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#신선한_해산물', 'seafood',            'B0103', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#달달한_디저트',   'dessert-good',       'B0103', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#가성비_최강맛집',     'value-for-money',    'B0103', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#예약_없으면_힘듦',     'reservation-required','B0103','N', 'Y', 'N');

/* ===================== B0104 문화/역사 ===================== */
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#갤러리_투어',   'exhibition',         'B0104', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#재밌는_박물관',   'museum',             'B0104', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#역사_탐방코스',          'heritage-site',      'B0104', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#전통시장_먹거리',        'traditional-market', 'B0104', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#전문가_해설투어',        'guided-tour',        'B0104', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#밤에도_열려요',        'night-opening',      'B0104', 'N', 'Y', 'N');

/* ===================== B0105 계절/자연 ===================== */
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#봄_벚꽃명소',       'cherry-blossom',     'B0105', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#가을_단풍스폿',       'autumn-foliage',     'B0105', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#여름_힐링해변',            'beach',              'B0105', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#한적한_산책길',          'walking-trail',      'B0105', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#야경_포인트',       'night-view',         'B0105', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#피크닉_추천지',     'picnic-spot',        'B0105', 'N', 'Y', 'N');

/* ===================== B0106 실버/교통약자 ===================== */
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#휠체어_편리', 'wheelchair-accessible','B0106','N','Y','N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#장애인_화장실',    'accessible-restroom','B0106', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#점자안내_있음',        'braille-guide',      'B0106', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#엘리베이터_완비',      'elevator',           'B0106', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#편한_경사로',          'ramp',               'B0106', 'N', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#저상버스_운행',    'low-floor-bus',      'B0106', 'N', 'Y', 'N');

/* ===================== 공용(공통) 태그 — TCATEGORY='B01' ===================== */
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#알찬여행구성','well-planned-trip',null,  'Y', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#트렌디해요','trendy',null,  'Y', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#가이드가_친절해요','kind-guide',null,  'Y', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#비싼만큼_가치가있어요',        'worth-it',null,  'Y', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#숙소가_좋았어요',      'good-stay',null,  'Y', 'Y', 'N');
INSERT INTO TAG (TAG_ID, LABEL, SLUG, TCATEGORY, COMMONYN, USEYN, RECOYN)
 VALUES (TAG_SEQ.NEXTVAL, '#가성비_좋아요',        'value-good',null,  'Y', 'Y', 'N');

