-- 안전 삭제
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHAT_ROOM CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CHAT_ROOM_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_CHAT_ROOM_BI'; EXCEPTION WHEN OTHERS THEN NULL; END;


-- 테이블
CREATE TABLE CHAT_ROOM (
    ROOM_ID       NUMBER(20)                      PRIMARY KEY,            -- 채팅방 ID
    BUYER_ID      NUMBER(10)                      NOT NULL,               -- 구매자 MEMBER.MEMBER_ID
    SELLER_ID     NUMBER(10)                      NOT NULL,               -- 판매자 MEMBER.MEMBER_ID
    PRODUCT_ID    NUMBER(10),                                             -- PRODUCT.PRODUCT_ID (nullable)
    STATUS        VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,           -- ACTIVE, CLOSED
    LAST_MSG_ID   NUMBER(20),                                             -- 마지막 메시지 ID (추후 FK)
    CREATED_AT    TIMESTAMP            DEFAULT SYSTIMESTAMP NOT NULL,     -- 생성 시각
    CLOSED_AT     TIMESTAMP                                               -- 종료 시각
);

-- 상태 체크
ALTER TABLE CHAT_ROOM
  ADD CONSTRAINT CK_CHAT_ROOM_STATUS CHECK (STATUS IN ('ACTIVE','CLOSED'));

-- 동일한 productId + buyerId + sellerId 조합은 ACTIVE 상태에서 단 하나만 허용
ALTER TABLE CHAT_ROOM
  ADD CONSTRAINT UK_CHAT_ROOM_ACTIVE
  UNIQUE (PRODUCT_ID, BUYER_ID, SELLER_ID, STATUS);


-- FK (회원 삭제시 대화방도 함께 제거가 필요하면 CASCADE, 보존하려면 SET NULL/RESTRICT로 바꿔도 됨)
ALTER TABLE CHAT_ROOM
  ADD CONSTRAINT FK_CHAT_ROOM_BUYER  FOREIGN KEY (BUYER_ID)
  REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE;

ALTER TABLE CHAT_ROOM
  ADD CONSTRAINT FK_CHAT_ROOM_SELLER FOREIGN KEY (SELLER_ID)
  REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE;

-- 상품은 삭제되더라도 채팅은 보존하고 싶을 가능성이 크므로 SET NULL 권장
ALTER TABLE CHAT_ROOM
  ADD CONSTRAINT FK_CHAT_ROOM_PRODUCT FOREIGN KEY (PRODUCT_ID)
  REFERENCES PRODUCT(PRODUCT_ID) ON DELETE SET NULL;

-- 시퀀스
CREATE SEQUENCE CHAT_ROOM_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 자동 채번 트리거
CREATE OR REPLACE TRIGGER TRG_CHAT_ROOM_BI
BEFORE INSERT ON CHAT_ROOM
FOR EACH ROW
BEGIN
  IF :NEW.ROOM_ID IS NULL THEN
    :NEW.ROOM_ID := CHAT_ROOM_SEQ.NEXTVAL;
  END IF;
END;


-- 조회/필터 성능용 인덱스
CREATE INDEX IX_CHAT_ROOM_STATUS_CREATED ON CHAT_ROOM (STATUS, CREATED_AT);
CREATE INDEX IX_CHAT_ROOM_BUYER       ON CHAT_ROOM (BUYER_ID);
CREATE INDEX IX_CHAT_ROOM_SELLER      ON CHAT_ROOM (SELLER_ID);
CREATE INDEX IX_CHAT_ROOM_PRODUCT     ON CHAT_ROOM (PRODUCT_ID);


COMMIT;