BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CHAT_MESSAGE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE CHAT_MESSAGE_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;


CREATE TABLE CHAT_MESSAGE (
  MSG_ID        NUMBER(20)       PRIMARY KEY,
  ROOM_ID       NUMBER(20)       NOT NULL,       -- CHAT_ROOM.ROOM_ID
  SENDER_ID     NUMBER(10)       NOT NULL,       -- MEMBER.MEMBER_ID
  CONTENT       VARCHAR2(2000)   NOT NULL,
  CREATED_AT    TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,
  READ_YN       CHAR(1)          DEFAULT 'N' CHECK (READ_YN IN ('Y','N')),
  CLIENT_MSG_ID VARCHAR2(64)     NULL
);

CREATE UNIQUE INDEX UK_CHATMSG_CLIENT ON CHAT_MESSAGE(CLIENT_MSG_ID);

CREATE SEQUENCE CHAT_MESSAGE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- (선택) FK: 방/보낸사람이 실제로 존재하는지까지 엄격히 보려면 아래 주석 해제
ALTER TABLE CHAT_MESSAGE ADD CONSTRAINT FK_CHATMSG_ROOM   FOREIGN KEY (ROOM_ID)   REFERENCES CHAT_ROOM(ROOM_ID) ON DELETE CASCADE;
ALTER TABLE CHAT_MESSAGE ADD CONSTRAINT FK_CHATMSG_SENDER FOREIGN KEY (SENDER_ID) REFERENCES MEMBER(MEMBER_ID)  ON DELETE CASCADE;


COMMIT;