CREATE USER c##mosi IDENTIFIED BY mosi1234 DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp PROFILE DEFAULT;
GRANT CONNECT, RESOURCE TO c##mosi;
GRANT CREATE VIEW, CREATE SYNONYM TO c##mosi;
GRANT UNLIMITED TABLESPACE TO c##mosi;
ALTER USER c##mosi ACCOUNT UNLOCK;